"""
Database Models for OpsPilotOS
Uses SQLModel (SQLAlchemy + Pydantic hybrid)
"""
from datetime import datetime
from typing import Optional
from sqlmodel import Field, SQLModel, JSON, Column
from sqlalchemy import Text


# ==================== Users & Organizations ====================
class User(SQLModel, table=True):
    """User account"""
    __tablename__ = "users"

    id: Optional[int] = Field(default=None, primary_key=True)
    email: str = Field(index=True, unique=True)
    hashed_password: str
    full_name: Optional[str] = None
    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Organization(SQLModel, table=True):
    """Organization/workspace"""
    __tablename__ = "organizations"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    owner_id: int = Field(foreign_key="users.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Membership(SQLModel, table=True):
    """User membership in organization"""
    __tablename__ = "memberships"

    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id")
    org_id: int = Field(foreign_key="organizations.id")
    role: str  # Owner, Admin, Operator, Viewer
    created_at: datetime = Field(default_factory=datetime.utcnow)


class APIKey(SQLModel, table=True):
    """API key for programmatic access"""
    __tablename__ = "api_keys"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    hashed_key: str = Field(index=True)
    org_id: int = Field(foreign_key="organizations.id")
    created_by: int = Field(foreign_key="users.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    last_used_at: Optional[datetime] = None
    is_active: bool = True


# ==================== Content Management ====================
class Project(SQLModel, table=True):
    """Project containing deliverables and KB"""
    __tablename__ = "projects"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    description: Optional[str] = None
    org_id: int = Field(foreign_key="organizations.id")
    created_by: int = Field(foreign_key="users.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = "active"  # active, archived


class KBDocument(SQLModel, table=True):
    """Knowledge base document"""
    __tablename__ = "kb_documents"

    id: Optional[int] = Field(default=None, primary_key=True)
    project_id: int = Field(foreign_key="projects.id")
    filename: str
    content_hash: str  # CAS hash
    content: str = Field(sa_column=Column(Text))
    indexed_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Deliverable(SQLModel, table=True):
    """Deliverable (content generated by agent)"""
    __tablename__ = "deliverables"

    id: Optional[int] = Field(default=None, primary_key=True)
    project_id: int = Field(foreign_key="projects.id")
    title: str
    description: Optional[str] = None
    status: str = "requested"  # requested, in_progress, completed, failed
    request_params: dict = Field(default={}, sa_column=Column(JSON))
    content_md_hash: Optional[str] = None  # CAS hash of markdown
    content_pdf_hash: Optional[str] = None  # CAS hash of PDF
    created_by: int = Field(foreign_key="users.id")
    completed_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ==================== Billing & Subscriptions ====================
class Plan(SQLModel, table=True):
    """Subscription plan"""
    __tablename__ = "plans"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(unique=True)
    price_monthly: float
    currency: str = "EUR"
    seats: int  # -1 for unlimited
    deliverables: int  # -1 for unlimited
    price_per_deliverable: float = 0.0
    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Subscription(SQLModel, table=True):
    """Organization subscription"""
    __tablename__ = "subscriptions"

    id: Optional[int] = Field(default=None, primary_key=True)
    org_id: int = Field(foreign_key="organizations.id")
    plan_id: int = Field(foreign_key="plans.id")
    status: str = "active"  # active, past_due, canceled
    current_period_start: datetime
    current_period_end: datetime
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Invoice(SQLModel, table=True):
    """Invoice"""
    __tablename__ = "invoices"

    id: Optional[int] = Field(default=None, primary_key=True)
    invoice_number: str = Field(unique=True, index=True)
    org_id: int = Field(foreign_key="organizations.id")
    subscription_id: Optional[int] = Field(default=None, foreign_key="subscriptions.id")
    status: str = "draft"  # draft, sent, paid, void
    currency: str = "EUR"
    subtotal: float = 0.0
    vat_rate: float = 0.0
    vat_amount: float = 0.0
    total: float = 0.0

    # VAT fields
    customer_vat_id: Optional[str] = None
    customer_country: Optional[str] = None
    reverse_charge: bool = False

    issued_at: Optional[datetime] = None
    due_at: Optional[datetime] = None
    paid_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


class InvoiceItem(SQLModel, table=True):
    """Invoice line item"""
    __tablename__ = "invoice_items"

    id: Optional[int] = Field(default=None, primary_key=True)
    invoice_id: int = Field(foreign_key="invoices.id")
    description: str
    quantity: int = 1
    unit_price: float
    amount: float
    created_at: datetime = Field(default_factory=datetime.utcnow)


class LedgerEntry(SQLModel, table=True):
    """Ledger entry (double-entry bookkeeping)"""
    __tablename__ = "ledger_entries"

    id: Optional[int] = Field(default=None, primary_key=True)
    account_code: str  # From chart of accounts
    invoice_id: Optional[int] = Field(default=None, foreign_key="invoices.id")
    description: str
    debit: float = 0.0
    credit: float = 0.0
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ==================== Tax/VAT ====================
class VATReport(SQLModel, table=True):
    """VAT report for a period"""
    __tablename__ = "vat_reports"

    id: Optional[int] = Field(default=None, primary_key=True)
    org_id: int = Field(foreign_key="organizations.id")
    period_start: datetime
    period_end: datetime
    total_sales: float = 0.0
    total_vat_collected: float = 0.0
    report_data: dict = Field(default={}, sa_column=Column(JSON))
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ==================== Support ====================
class Ticket(SQLModel, table=True):
    """Support ticket"""
    __tablename__ = "tickets"

    id: Optional[int] = Field(default=None, primary_key=True)
    org_id: int = Field(foreign_key="organizations.id")
    created_by: int = Field(foreign_key="users.id")
    title: str
    description: str = Field(sa_column=Column(Text))
    status: str = "open"  # open, in_progress, resolved, closed
    priority: str = "normal"  # low, normal, high, urgent
    assigned_to: Optional[int] = Field(default=None, foreign_key="users.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ==================== HITL (Human-in-the-Loop) ====================
class HITLRequest(SQLModel, table=True):
    """Human-in-the-loop approval request"""
    __tablename__ = "hitl_requests"

    id: Optional[int] = Field(default=None, primary_key=True)
    org_id: int = Field(foreign_key="organizations.id")
    action: str
    agent_id: Optional[str] = None
    reason: str
    params: dict = Field(default={}, sa_column=Column(JSON))
    status: str = "pending"  # pending, approved, rejected
    approved_by: Optional[int] = Field(default=None, foreign_key="users.id")
    approved_at: Optional[datetime] = None
    # M1.1: Override token support
    override_token_hash: Optional[str] = None  # SHA-256 hash of issued override token
    consumed_at: Optional[datetime] = None  # When override token was used (one-time-use)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ==================== Audit Events ====================
class AuditEventDB(SQLModel, table=True):
    """Audit event (also stored in JSONL, this is for querying)"""
    __tablename__ = "audit_events"

    id: Optional[int] = Field(default=None, primary_key=True)
    event_id: str = Field(unique=True, index=True)
    timestamp: datetime
    event_type: str
    agent_id: Optional[str] = None
    user_id: Optional[int] = None
    action: str
    params: dict = Field(default={}, sa_column=Column(JSON))
    result: Optional[dict] = Field(default=None, sa_column=Column(JSON))
    decision: Optional[str] = None
    previous_hash: str = ""
    event_hash: str = Field(index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
